trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Firstjob
    steps: 
    - bash: echo Build firstjob
    - bash: echo $(PipelineLevelVariable)
  - job: Secondjob
    steps: 
    - bash: echo Build secondjob  
- stage: DevDeploy
  variables:
    environment: Dev
  dependsOn: Build
  jobs:
  - job: DevDeploy
    steps: 
    - bash: echo DevDeploy firstjob
    - bash: echo $(environment)Developjob

- stage: QADeploy
  variables:
    environment: QA
  dependsOn: Build 
  jobs:
  - job: QADeployjob
    steps: 
    - bash: echo QADeploy firstjob
    - bash: echo $(environment)QAdeployment

- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
  - job: Prodedeployjob
    steps: 
    - bash: echo Prodedeploy firstjob

